---
# These tasks are responsible for copying the latest code from
# the version control system.

- name: Copy the code from repository
  git:
    repo: "{{ repo }}"
    dest: /var/www/html/

- name: Creates the index.php file
  template:
    src: db.php.j2
    dest: /var/www/html/db.php